### ISSUE TITLE
PageAnalyzer 报错

### ISSUE THREAD

**Issue by supermebing** [fluttify-project/janalytics_fluttify#1]
navigatorObservers: [
              PageAnalyzer(),
              BotToastNavigatorObserver(),
            ],

The class 'PageAnalyzer' doesn't have a default constructor.
Try using one of the named constructors defined in 'PageAnalyzer'.

**Comment by yohom** [comment]
`PageAnalyzer`是单例，使用`PageAnalyzer.instance`
