### ISSUE TITLE
请更新插件的依赖，需求的JCore版本与jPush_flutter插件要求的不一致

### ISSUE THREAD

**Issue by RA1NO3O** [fluttify-project/janalytics_fluttify#2]
[!] CocoaPods could not find compatible versions for pod "JCore":
  In Podfile:
    janalytics_fluttify (from `.symlinks/plugins/janalytics_fluttify/ios`) was resolved to 0.0.1, which depends on
      JAnalytics (= 2.1.2) was resolved to 2.1.2, which depends on
        JCore (< 3.0.0, >= 1.2.0)

    jcore_fluttify (from `.symlinks/plugins/jcore_fluttify/ios`) was resolved to 0.0.1, which depends on
      JCore (= 2.4.0)

    jpush_flutter (from `.symlinks/plugins/jpush_flutter/ios`) was resolved to 0.0.2, which depends on
      JCore (= 2.6.2)

**Comment by RA1NO3O** [comment]
走投无路了。。官方的flutter极光分析插件根本跑不起来

**Comment by supermebing** [comment]
请问是怎么解决的
